language: python
python:
- '3.4'
- '3.7'
install:
- pip install -r requirements.pip
- pip install tox-travis
script: tox
deploy:
  provider: pypi
  on:
    branch: master
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  password:
    secure: MuwWp+PrezNv3s60zJVdte8VE0bg3yDfI/Gw6ZnW/8I0Vhlir1ldvPysLTB+wMDjfAlt3FgbXQkGsI6bF19SOUDZaNeuXKIVJIJ9DJOHoIA4g7PAfOAoDTyQBPyYUPKIdpfP8cOwxfTqqDQWV0PCAB9KzNi8tMl+GSpC0pEW25FS2DKiaqWv56ERi9RaGhm0O/KEPZ73MSMmU+D6ZWu6GfzMp7TVBtltcOkt8+qUb6bMhB89/HldLOGlAWdoqpRLsrQpNIRp2vngT+FE2xpVzHgEe38SbKOgDGjnuI5GeiM2uHO0KUnK8/h8X39DBInDYfTT/unULhASVXqPsm8rIiUT2PyB2Z0whqMgCx+qNXszzZFcJHc5eo3QtB+GSipNG1fS/KOzV/mtziRacUdi7xEWmMgizf4cPYBW7WCNb5AxbVmFRGpaYfGt5xuQsg/LHrLIv80zHDqc918EvQUdrOvyQYmSq0Ydh/ElTPT/pzmM06gkhJfFB3vjUbz3O3YBR4Elie1rszeaOLcCuNVew5eneU7zksT/xqHl2b+4tgy04oFUZvbUXA4IOSYk4jmcHgzJLprNO9CrSINk2hhzZTFQ5ORIa2qCqsdXLNzKxMZxq4W/TlwmGEF4mt7csBEQ2h4gaHdHCCi4uHdMDi/9hsbt1pjrjjVhHruUnqr405k=
  username:
    secure: JhLffSYa/ES20jPiXmmEwEq6jLwpd2VEDe3KT+iqZ6LPygxCFjyoT8rI7LBz91PsjjBZa1jVFw7kAdtT6RvLOFHp3Pol87ULpmM8PBD++FIShxPFds2p+5UzEvQ/D3+6E9gxeHIwNQk6RGwYm4hF7kGaWQwhtD+Y3mXhL4pjvtGy+3rkXWHhe0LNvRdCUqogsv7EXBhRZunb/KqLW7rtn7NlTnBVz+Sf97GPuNtgmMG2UPnCcsip0V+hUgMcpMXqlVbPpFNfq2k901qKfRMgg4hjum6ML+oKCqiXFzH/cTCj9okNzK56yAkSN3lrfUPKHIVAfLAYDXexFCTDpbr970XnTtpFBlqzBnB8W4dYXrBb00j3vWy3yJrXZSQSwn8ETUBC4ObSKFJseIA0OFMlUoBHkVyLo0iH30VGGAlI0p3FXY+DBSQxIvyCIlbHbmHEcPlKyb6K5sEZgAT6mqPiPi0d6MnDNXF4R5+LAI0uZhr0EzXZkKoP0wH1DUoR72NJIyfGPKEvmY/os86UcvI9fGKCaqC15I2gMoKBWJ2s7xjiDvZ5Hi1vhK/kP2rQnGDrUd2wclhufMARiW0KYhJsfgMj4Q5ICQ4bMP3SWuXRc9A6toMLnH82z0r2sPLv8OFidbPW9wq4tnfZ0+WtJ2p+FARauEStHeVXdpfwkZds25I=
after_success:
- coveralls
