language: python
python:
- '2.7'
install: pip install -r requirements.pip
script: bash ./run_coverage.sh
deploy:
  provider: pypi
  on:
    branch: master
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  password:
    secure: PIQYJCwevJtRZPxuRo5HKe7qlrOyx2rbqofOCwZFqEe1GQZA7ZjQptlQyI3+JOb5lcrXKW0AUuW5fdJ8inGug4Cb0Pg9FJqcCu++m3WHS+ybv+zU8AuVS3pQ+4ireO98l6+4g4TfBC8NQLEJFf07AOktJl5WKBCu+VD4K8tnKNDtm7rkoAu2cqKzQa4heKE4n65jshsZkl8LY1arNzyVQBGXrXedhy8T7RfFcrVcjN3nOvDSEuifTOvZhVu05DLxOwJh3CH8Or9UxgKtNb1PDOqxjyBJ5LywBZmqPNMgjIlaysNszIwtBefLRqrW9U/3OrhDcOAcPGvdT+M/pLU0OS/aCeBMopPDi4Y3yAEZZw3idEoOT7hmOdq1IOLLpVu6EuxnSl7h03t4LEbAAZd9vWVAmBrm6cN6vQ9QiwtSORM9vXNNuilTAkZRZjCk662uSK/+arnPyqpw+tThND3SJ62ls1O0EtlSCJThlXGAZB+FWC3sY5Uo1CALqc22jYHnFLnjwuIGjrBQBvct1P7zghIrbonAb9d4dO0nM1uelRfe8NQTL7ffZcBRnhFITOocMx+S6YrMle4ln6Ot8McMK4erQi4M5dMWvCsOsmMeb5D8eI9EwewS41jn12ZFCnV7piWEQhbjJz4falIUkgWon6yL7Bbu5FuxWefOkLd/9rM=
  username:
    secure: JhLffSYa/ES20jPiXmmEwEq6jLwpd2VEDe3KT+iqZ6LPygxCFjyoT8rI7LBz91PsjjBZa1jVFw7kAdtT6RvLOFHp3Pol87ULpmM8PBD++FIShxPFds2p+5UzEvQ/D3+6E9gxeHIwNQk6RGwYm4hF7kGaWQwhtD+Y3mXhL4pjvtGy+3rkXWHhe0LNvRdCUqogsv7EXBhRZunb/KqLW7rtn7NlTnBVz+Sf97GPuNtgmMG2UPnCcsip0V+hUgMcpMXqlVbPpFNfq2k901qKfRMgg4hjum6ML+oKCqiXFzH/cTCj9okNzK56yAkSN3lrfUPKHIVAfLAYDXexFCTDpbr970XnTtpFBlqzBnB8W4dYXrBb00j3vWy3yJrXZSQSwn8ETUBC4ObSKFJseIA0OFMlUoBHkVyLo0iH30VGGAlI0p3FXY+DBSQxIvyCIlbHbmHEcPlKyb6K5sEZgAT6mqPiPi0d6MnDNXF4R5+LAI0uZhr0EzXZkKoP0wH1DUoR72NJIyfGPKEvmY/os86UcvI9fGKCaqC15I2gMoKBWJ2s7xjiDvZ5Hi1vhK/kP2rQnGDrUd2wclhufMARiW0KYhJsfgMj4Q5ICQ4bMP3SWuXRc9A6toMLnH82z0r2sPLv8OFidbPW9wq4tnfZ0+WtJ2p+FARauEStHeVXdpfwkZds25I=
after_success:
  - coveralls

